class Constants:

    CPU = 'cpu'
    CUDA = 'cuda'
    EXTN_MODEL = '.pth'
    EXTN_NUMPY = '*.npy'
    EXTN_SHARD = '.tar'
    PNG_TRAINING_HISTORY = 'training_history.png'
    SAMPLE_ID = 'sample_id'
    SEIS = 'seis'
    TOTAL_IN_GB = 'total_in_gb'
    TRAIN = 'train'
    USAGE_IN_GB = 'usage_in_gb'
    USAGE_IN_PERCENT = 'usage_in_percent'
    VAL = 'val'
    VEL = 'vel'
